require 'rbconfig'

is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)

jailhost_ip = '10.0.5.10'
jailhost_ssh_port = 5022
bootstrap_ip = '10.0.5.11'
bootstrap_ssh_port = 5122

Vagrant.configure('2') do |config|
  # https://stackoverflow.com/questions/28471542/cant-ssh-to-vagrant-vms-using-the-insecure-private-key-vagrant-1-7-2
  # config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'

  config.vm.define 'jailhost' do |jailhost|
    config.vm.box = "bento/freebsd-12"

    jailhost.vm.network 'private_network', ip: jailhost_ip
    jailhost.vm.network 'forwarded_port', guest: 22, host: jailhost_ssh_port, id: 'ssh'

    # this line has to be here to disable the default, otherwise NFS is required but we don't need it
    jailhost.vm.synced_folder '.', '/vagrant', disabled: true

    jailhost.vm.provider 'virtualbox' do |vb|
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    jailhost.vm.provision 'shell', inline: 'pkg install --yes lang/python2', privileged: true
  end

  config.vm.define 'bootstrap' do |bootstrap|
    bootstrap.vm.box = 'generic/ubuntu2010'

    bootstrap.vm.network 'private_network', ip: bootstrap_ip
    bootstrap.vm.network 'forwarded_port', guest: 22, host: bootstrap_ssh_port, id: 'ssh'

    # set dir and file modes to minimize ansible confusion
    bootstrap.vm.synced_folder '..', '/vagrant', :mount_options => ["dmode=777","fmode=666"]

    bootstrap.vm.provider 'virtualbox' do |vb|
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end

    # install vagrant host insecure_private_key to use when connecting to jailhost with ansible from bootstrap vm
    bootstrap.vm.provision 'file', source: '.vagrant/machines/jailhost/virtualbox/private_key', destination: '~/vagrant_insecure_private_key'
    bootstrap.vm.provision 'shell', path: 'bootstrap-provision.sh', args: [jailhost_ip], privileged: false
  end
end